import {Injectable} from '@angular/core';
import {CanActivate, ActivatedRouteSnapshot, RouterStateSnapshot} from '@angular/router';
import {KeycloakService} from './keycloak.service';


// Generated by https://github.com/ssilvert/keycloak-schematic/wiki/Getting-Started

@Injectable()
export class KeycloakGuard implements CanActivate {
    constructor(private keycloakService: KeycloakService) {}

    canActivate(route: ActivatedRouteSnapshot,
                state: RouterStateSnapshot): boolean {
        if (this.keycloakService.authenticated()) {
            return true;
        }

        this.keycloakService.login({redirectUri: this.getOrigin() + state.url});
        return false;
    }

    getOrigin() {
        if (!window.location.origin) {
            return window.location.protocol + '//' + window.location.hostname + (window.location.port ? ':' + window.location.port : '');
        } else {
            return window.location.origin;
        }
    }
}
